CREATE TABLE users
(
    user_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR                                             NOT NULL,
    email   VARCHAR                                             NOT NULL
);

CREATE TABLE events
(
    event_id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    annotation        VARCHAR(2000)                                       NOT NULL,
    category_id       BIGINT                                              NOT NULL,
    created_on        TIMESTAMP                                           NOT NULL,
    description       VARCHAR(7000)                                       NOT NULL,
    event_date        TIMESTAMP                                           NOT NULL,
    initiator_id      BIGINT                                              NOT NULL,
    location_id       BIGINT                                              NOT NULL,
    paid              BOOLEAN                                             NOT NULL,
    participantLimit  INT                                                 NOT NULL,
    requestModeration BOOLEAN                                             NOT NULL,
    published_on      TIMESTAMP,
    state             VARCHAR(10)                                         NOT NULL,
    title             VARCHAR(120)                                        NOT NULL,
    views             BIGINT                                              NOT NULL,
    CONSTRAINT events_initiator FOREIGN KEY (initiator_id) REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT events_location FOREIGN KEY (location_id) REFERENCES locations (location_id) ON DELETE RESTRICT,
    CONSTRAINT events_category FOREIGN KEY (category_id) REFERENCES categories (category_id) ON DELETE RESTRICT
);

CREATE TABLE categories
(
    category_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR                                             NOT NULL UNIQUE
);

CREATE TABLE requests
(
    requester_id BIGINT PRIMARY KEY NOT NULL,
    event_id     BIGINT PRIMARY KEY NOT NULL,
    created      TIMESTAMP          NOT NULL,
    status       VARCHAR(10)        NOT NULL
);

CREATE TABLE compilations
(
    compilation_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title          VARCHAR                                             NOT NULL,
    pinned         BOOLEAN                                             NOT NULL
);

CREATE TABLE compilations_events
(
    compilation_id BIGINT PRIMARY KEY NOT NULL,
    event_id       BIGINT PRIMARY KEY NOT NULL
);

CREATE TABLE locations
(
    location_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR                                             NULL,
    lat         FLOAT                                               NOT NULL,
    lon         FLOAT                                               NOT NULL
);
